package no.bibsys.aws.apigateway;


/**
 * Helper class for parsing Server information taken from OpenApi specification generated by ApiGateway.
 */
public class ServerInfo {

    private static final String basePathString = "/{basePath}";
    private static final String basePathStringRegex = "/\\{basePath}";
    private final String serverUrl;
    private final String stage;

    public ServerInfo(String serverUrl, String stage) {
        this.serverUrl = serverUrl;

        if (serverUrl.contains(basePathString) && stage.charAt(0) == '/') {
            this.stage = stage.substring(1);
        } else {
            this.stage = stage;
        }
    }

    /**
     * It returns the Server URL in the form of https://xxxxxxxx.execute-api.eu-west-1.amazonaws.com/{basePath}. It is
     * intended for to be used by Swagger and SwaggerHub.
     *
     * @return the Server url to use in the OpenApi specification.
     */
    public String getServerUrl() {
        return serverUrl;
    }


    /**
     *  Gets the ApiGateway stage.
     * @return The ApiGateway Stage for the API. Swagger will use this value to replace {@code {basePath}}
     */
    public String getStage() {
        return stage;
    }


    /**
     *  Retrieves the server address.
     * @return The Server URL where {@code {basepath}} and "http(s)://" has been removed.
     */
    public String serverAddress() {
        return serverUrl.replaceAll("(http(s?))://", "").replaceAll(basePathStringRegex, "");
    }
}
